package:
  name: medfiltmp
  version: '0.1'

source:
  git_url: https://github.com/kyuepublic/medfiltmp.git

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy

  run:
    - python
    - cython
    - numpy
    - scipy
    - scikit-image
    - scipy

test:
  # Python imports
  imports:
    - medfiltmp

about:
  home: https://github.com/kyuepublic/medfiltmp.git
  license: BSD-3
  summary: 'multi processing version of 3d filter.'